name: 'Trigger Notification Workflow'
description: 'Triggers the notification workflow defined in .github/workflows/notifier.yml'
author: 'naan-mxco'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
outputs:
  status:
    description: 'The status of the execution'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Trigger Notification Workflow
      run: |
        echo "Running notification workflow..."
        github_token=$1
        curl -X POST \
          -H "Authorization: token $github_token" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/naan-mxco/pocket/actions/workflows/notifier.yml/dispatches \
          -d '{"ref":"main"}'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
